spiderpig/spiderpig/models/base.py
from spiderpig.base import DB
from spiderpig.models.mixin_base import CreatedMixin, CRUDMixin, PrimaryMixin
from spiderpig.models.mixin_urls import ValueIntMixin, ValueStrMixin


class Model(CreatedMixin, PrimaryMixin, CRUDMixin, DB.Model):
    __table_args__ = {'extend_existing': True}
    __abstract__ = True


class UrlIntModel(ValueIntMixin, Model):
    __abstract__ = True


class UrlStrModel(ValueStrMixin, Model):
    __abstract__ = True


def db_pri_col(name: str, nullable: bool = True):
    name = '{}.prime'.format(name)
    return DB.Column(DB.Integer(), DB.ForeignKey(name), nullable=nullable)


def db_ref_rel(tbl: str, bref: str, *, self_rel: bool = False):
    return DB.relationship(
        tbl, backref=bref, lazy='joined',
        remote_side='{}.prime'.format(tbl) if self_rel else None,
        order_by='{}.created.desc()'.format(tbl),
    )

spiderpig/spiderpig/views/crawl.py
from flask import (
    Blueprint, Response, abort, render_template, request, stream_with_context,
)
from flask.json import dumps

from flask_login import current_user, login_required
from spiderpig.crawl.spider import Spider
from spiderpig.fixed import FORM_CRAWL_TTL_DEFAULT
from spiderpig.forms.crawl import SnapForm

BLUEPRINT_CRAWL = Blueprint('crawl', __name__, url_prefix='/crawl')


@BLUEPRINT_CRAWL.route('/', methods=['GET', 'POST'])
@login_required
def index():
    form = SnapForm(
        address=request.args.get('address'),
        ttl=request.args.get('ttl', FORM_CRAWL_TTL_DEFAULT),
    )
    submitted = form.validate_on_submit()

    return render_template(
        'crawl/index.html',
        title='Crawl',
        form=form,
        submitted=submitted,
    )


@BLUEPRINT_CRAWL.route('/snap', methods=['POST'])
@login_required
def snap():
    address = request.values.get('address', None)
    ttl = request.values.get('ttl', None)
    if not address or not ttl:
        abort(400)
    try:
        ttl = int(ttl)
    except ValueError:
        abort(400)

    spider = Spider()
    def collect():
        for elem in spider(address=address, ttl=ttl, user=current_user):
            yield '{}\n\t\t\n'.format(dumps(elem.view()))

    return Response(
        stream_with_context(collect()),
        status=200,
        mimetype='text/plain'
    )

spiderpig/spiderpig/views/main.py
from flask import Blueprint, render_template

from spiderpig.fixed import (
    LATEST_CRAWL_NUM, LATEST_URL_NUM, LATEST_USER_NUM, PAGE_CRAWL_NUM,
    PAGE_URL_NUM, PAGE_USER_NUM,
)
from spiderpig.models.crawl import Crawl
from spiderpig.models.url import Url
from spiderpig.models.user import User

BLUEPRINT_MAIN = Blueprint('main', __name__)


@BLUEPRINT_MAIN.route('/')
def index():

    num_url = Url.query.count()
    num_url_fail = Url.query_filter_fail().count()
    num_url_good = (num_url - num_url_fail)

    return render_template(
        'main/index.html',
        num_user=User.query.count(),
        num_crawl=Crawl.query.count(),
        num_url=num_url,
        num_url_fail=num_url_fail,
        num_url_good=num_url_good,
        lat_user=User.query_order_created().limit(LATEST_USER_NUM).all(),
        lat_crawl=Crawl.query_order_created().limit(LATEST_CRAWL_NUM).all(),
        lat_url=Url.query_order_created().limit(LATEST_URL_NUM).all(),
    )


@BLUEPRINT_MAIN.route('/users/<int:page>')
@BLUEPRINT_MAIN.route('/users/')
@BLUEPRINT_MAIN.route('/users')
def users(page=None):

    return render_template(
        'main/user.html',
        title='Users',
        users=User.query_order_created().paginate(
            page, per_page=PAGE_USER_NUM
        ),
    )


@BLUEPRINT_MAIN.route('/user/<int:prime>')
def user_single(prime):
    user = User.query.get_or_404(prime)

    return render_template(
        'main/user.html',
        title='{} User'.format(user.username),
        user=user,
    )


@BLUEPRINT_MAIN.route('/crawls/<int:page>')
@BLUEPRINT_MAIN.route('/crawls/')
@BLUEPRINT_MAIN.route('/crawls')
def crawls(page=None):

    return render_template(
        'main/crawl.html',
        title='Crawls',
        crawls=Crawl.query_order_created().paginate(
            page, per_page=PAGE_CRAWL_NUM
        ),
    )


@BLUEPRINT_MAIN.route('/crawl/<int:prime>')
def crawl_single(prime):
    crawl = Crawl.query.get_or_404(prime)

    return render_template(
        'main/crawl.html',
        title='Crawl details',
        crawl=crawl,
    )


@BLUEPRINT_MAIN.route('/urls/<int:page>')
@BLUEPRINT_MAIN.route('/urls/')
@BLUEPRINT_MAIN.route('/urls')
def urls(page=None):

    return render_template(
        'main/url.html',
        title='URLs',
        urls=Url.query_order_created().paginate(
            page, per_page=PAGE_URL_NUM
        ),
    )


@BLUEPRINT_MAIN.route('/url/<int:prime>')
def url_single(prime):
    url = Url.query.get_or_404(prime)

    return render_template(
        'main/url.html',
        title='URL details',
        url=url,
    )


@BLUEPRINT_MAIN.route('/urls/good/<int:page>')
@BLUEPRINT_MAIN.route('/urls/good/')
@BLUEPRINT_MAIN.route('/urls/good')
def urls_good(page=None):

    return render_template(
        'main/url.html',
        title='Good URLs',
        urls=Url.query_filter_good(
            query=Url.query_order_created()
        ).paginate(
            page, per_page=PAGE_URL_NUM
        )
    )


@BLUEPRINT_MAIN.route('/urls/fail/<int:page>')
@BLUEPRINT_MAIN.route('/urls/fail/')
@BLUEPRINT_MAIN.route('/urls/fail')
def urls_fail(page=None):

    return render_template(
        'main/url.html',
        title='Failed URLs',
        urls=Url.query_filter_fail(
            query=Url.query_order_created()
        ).paginate(
            page, per_page=PAGE_URL_NUM
        )
    )

spiderpig/spiderpig/views/user.py
from flask import (
    Blueprint, abort, current_app, flash, redirect, render_template, request,
    url_for,
)

from flask_login import current_user, login_required, login_user, logout_user
from spiderpig.base import LMAN
from spiderpig.forms.user import ChangeForm, LoginForm, RegisterForm
from spiderpig.models.user import User

BLUEPRINT_USER = Blueprint('user', __name__, url_prefix='/user')


@LMAN.user_loader
def load_user(user_prime):
    return User.by_prime(user_prime)


def redirect_user_next():
    if not current_user.is_authenticated:
        return None
    redir = request.args.get('next')
    return redirect(redir if redir else url_for('user.home'))


@BLUEPRINT_USER.route('/logout')
@login_required
def logout():
    logout_user()
    flash('See you soon!', 'is-success')
    return redirect(url_for('main.index'))


@BLUEPRINT_USER.route('/login', methods=['GET', 'POST'])
def login():
    redir = redirect_user_next()
    if redir:
        return redir

    form = LoginForm()

    if form.validate_on_submit():
        user = form.retrieve()
        if user:
            flash('Welcome {}!'.format(user.username), 'is-success')
            login_user(user, remember=form.remember.data)
            redir = redirect_user_next()
            if redir:
                return redir

    return render_template(
        'user/handle.html',
        title='Login',
        form=form,
    )


@BLUEPRINT_USER.route('/register', methods=['GET', 'POST'])
def register():
    redir = redirect_user_next()
    if redir:
        return redir

    if not current_app.config['OPEN_REGISTRATION']:
        abort(404)

    form = RegisterForm()

    if form.validate_on_submit():
        user = form.retrieve()
        if user:
            flash('Hello {}! You are new here!'.format(user.username))
            login_user(user, remember=False)
            redir = redirect_user_next()
            if redir:
                return redir

    return render_template(
        'user/handle.html',
        title='Register',
        form=form,
    )


@BLUEPRINT_USER.route('/change', methods=['GET', 'POST'])
@login_required
def change():
    user = User.by_prime(current_user.prime)

    form = ChangeForm(icon=user.icon)

    if form.validate_on_submit():
        if form.retrieve(user):
            flash('Changed!')
            redir = redirect_user_next()
            if redir:
                return redir

    return render_template(
        'user/change.html',
        title='Change',
        form=form,
    )

@BLUEPRINT_USER.route('/home')
@login_required
def home():
    user = User.by_prime(current_user.prime)

    return render_template(
        'user/home.html',
        title='{} Home'.format(user.username),
        user=user,
    )

spiderpig/spiderpig/templates/macros/base.html
{% macro nothing_there(title='Nothing there!', icon='fa-spider') %}
    <div class="card">
        <div class="content">
            <div class="card-content">
                <div class="media">
                    <div class="media-left">
                        <div class="icon is-large">
                            <i class="fas fa-3x {{ icon }}"></i>
                        </div>
                    </div>
                    <div class="media-content">
                        <p class="title is-4">
                            {{ title }}
                        </p>
                        <p class="subtitle is-6">
                            <a href="{{ url_for('main.index') }}">
                                {{ config.APP_NAME }}
                            </a>
                            &mdash;
                            {{ config.APP_SUBTITLE }}
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endmacro %}

spiderpig/spiderpig/templates/macros/creds.html
{% macro reg_log_toggle() %}
    {% if config.OPEN_REGISTRATION %}
    {% with (is_reg, is_log) = (
        request.endpoint == 'user.register',
        request.endpoint == 'user.login'
    ) %}
    {% if is_reg or is_log %}
    <div class="tabs is-centered is-boxed is-medium">
        <ul>
            <li class="{{ 'is-active' if is_reg }}">
                <a href="{{ url_for('user.register') }}">
                    <span class="icon">
                        <i class="fas fa-user-plus"></i>
                    </span>
                    <span>Register</span>
                </a>
            </li>
            <li class="{{ 'is-active' if is_log }}">
                <a href="{{ url_for('user.login') }}">
                    <span class="icon">
                        <i class="fas fa-user-check"></i>
                    </span>
                    <span>Login</span>
                </a>
            </li>
        </ul>
    </div>
    {% endif %}
    {% endwith %}
    {% endif %}
{% endmacro %}

spiderpig/spiderpig/templates/macros/form.html
{% macro render_form(form, action=none) %}
    {% macro _field(fld) %}
        {% if fld.type in ['CSRFTokenField', 'HiddenField'] %}
            {{ fld() }}
        {% else %}
        <div class="field">
            {% with error_class = ' is-danger' if fld.errors else '' %}
            <div class="control">
            {% if fld.type in ['SubmitField'] %}
                {{ fld(class='button is-link') }}
            {% elif fld.type in ['StringField', 'PasswordField'] %}
                {{ fld.label(class='label') }}
                {{ fld(class='input' ~ error_class, placeholder=fld.description) }}
            {% elif fld.type in ['IntegerField'] %}
                {{ fld.label(class='label') }}
                {{ fld(class='input' ~ error_class, type='number', placeholder=fld.description) }}
            {% elif fld.type in ['BooleanField'] %}
                {{ fld(class='checkbox' ~ error_class) }}
                {{ fld.label(class='checkbox') }}
            {% elif fld.type in ['SelectField'] %}
                {{ fld.label(class='label') }}
                <div class="select">{{ fld() }}</div>
            {% else %}
                {{ fld.label(class='label') }}
                {{ fld(class='input') }}
            {% endif %}
            {% for error in fld.errors %}
                <p class="help is-danger">{{ error }}</p>
            {% endfor %}
            </div>
            {% endwith %}
        </div>
        {% endif %}
    {% endmacro %}
    {% if form %}
        <form method="post" action="{{ action if action else request.url }}">
        {% for field in form %}
            {{ _field(field) }}
        {% endfor %}
        </form>
    {% endif %}
{% endmacro %}

spiderpig/spiderpig/templates/macros/lists.html
{% macro _table(elems, heads) %}
    <table class="table is-striped is-narrow is-fullwidth is-hoverable">
        <thead>
            <tr>
            {% for head in heads %}
                <th>{{ head }}</th>
            {% endfor %}
            </tr>
        </thead>
        <tbody>
        {% for elem in elems %}
            <tr>{{ caller(elem) }}</tr>
        {% endfor %}
        </tbody>
    </table>
{% endmacro %}


{% macro users_list(users) %}
    {% call(user) _table(users, [
        'Username', 'Created', 'Last Login', 'Crawls'
    ]) %}
        <td>
            <span class="icon" style="display: inline-table;">
                <i class="fas {{ user.icon }}"></i>
            </span>
            <a href="{{ url_for('main.user_single', prime=user.prime) }}">
                {{ user.username }}
            </a>
        </td>
        <td>{{ user.created|moment }}</td>
        <td>{{ user.last_login|moment }}</td>
        <td>{{ user.crawls|length }}</td>
    {% endcall %}
{% endmacro %}

{% macro crawls_list(crawls, show_user=true) %}
    {% call(crawl) _table(crawls, [
        'Time', 'TTL', 'URLs', 'User'
    ] if show_user else [
        'Time', 'TTL', 'URLs'
    ]) %}
        <td>
            <a href="{{ url_for('main.crawl_single', prime=crawl.prime) }}">
                {{ crawl.created|moment }}
            </a>
        </td>
        <td>{{ crawl.ttl }}</td>
        <td>{{ crawl.urls|length }}</td>
        {% if show_user %}
        <td>
            <a href="{{ url_for('main.user_single', prime=crawl.user.prime) }}">
                {{ crawl.user.username }}
            </a>
        </td>
        {% endif %}
    {% endcall %}
{% endmacro %}

{% macro urls_list(urls, show_crawls=true) %}
    {% call(url) _table(urls, [
        'Time', '', 'Result', 'Children', 'Hop', 'Crawl'
    ] if show_crawls else [
        'Time', '', 'Result', 'Children', 'Hop'
    ]) %}
        <td>
            <a href="{{ url_for('main.url_single', prime=url.prime) }}">
                {{ url.created|moment }}
            </a>
        </td>
        <td class="has-text-centered">
            {% with (icls, icon) = (
                'has-text-success', 'fa-award'
            ) if url.status.good else (
                'has-text-danger', 'fa-fire-alt'
            ) %}
            <span class="icon {{ icls }}">
                <i class="fas {{ icon }}"></i>
            </span>
            {% endwith %}
            <div><strong>{{ url.status.value }}</strong></div>
        </td>
        <td>
            <div>
                <a href="{{ url.address }}">
                    {{ url.address|truncate(config.TRUNCATE, end='...') }}
                </a>
            </div>
            {% if url.error.value %}
                <div class="has-text-centered">
                    <code>{{ url.error.value }}</code>
                </div>
            {% endif %}
        </td>
        <td>
            {{ url.children|length }}
        </td>
        <td>
            {{ url.hop }}
        </td>
        {% if show_crawls %}
        <td>
            <a href="{{ url_for('main.crawl_single', prime=url.crawl.prime) }}">
                {{ url.crawl.prime }}
            </a>
        </td>
        {% endif %}
    {% endcall %}
{% endmacro %}

spiderpig/spiderpig/templates/macros/page.html
{% macro pagination(pgn) %}
    <nav class="pagination is-centered" role="navigation">
        {% with (href, dlbd) = (
            url_for(request.endpoint, page=pgn.prev_num) if pgn.has_prev,
            'disabled' if not pgn.has_prev
        ) %}
        <a class="pagination-previous" href="{{ href }}" {{ dlbd }}>
            <span class="icon">
                <i class="fas fa-arrow-left"></i>
            </span>
        </a>
        {% endwith %}
        {% with (href, dlbd) = (
            url_for(request.endpoint, page=pgn.next_num) if pgn.has_next,
            'disabled' if not pgn.has_next
        ) %}
        <a class="pagination-next" href="{{ href }}" {{ dlbd }}>
            <span class="icon">
                <i class="fas fa-arrow-right"></i>
            </span>
         </a>
        {% endwith %}
        <ul class="pagination-list">
        {% for page in pgn.iter_pages(
            left_edge=1, left_current=3,
            right_current=4, right_edge=1
        ) %}
            <li>
            {% if page %}
                {% with (href, curr) = (
                    url_for(request.endpoint, page=page),
                    'is-current' if page == pgn.page
                ) %}
                <a class="pagination-link {{ curr }}" href="{{ href }}">
                    {{ page }}
                </a>
                {% endwith %}
            {% else %}
                <span class="pagination-ellipsis">...</span>
            {% endif %}
            </li>
        {% endfor %}
        </ul>
    </nav>
{% endmacro %}

spiderpig/spiderpig/templates/macros/single.html
{% from 'macros/lists.html' import crawls_list %}
{% from 'macros/lists.html' import urls_list %}

{% macro _card(footer=none) %}
    <div class="content">
        <div class="card">
            <div class="card-content">
                {{ caller() }}
            </div>
            {% if footer %}
            <div class="card-footer">
                {{ footer }}
            </div>
            {% endif %}
        </div>
    </div>
{% endmacro %}
{% macro _media(icon, title, subtitle) %}
    <div class="media">
        <div class="media-left">
            <div class="icon is-large">
                <i class="fas fa-3x {{ icon }}"></i>
            </div>
        </div>
        <div class="media-content">
            <div class="title is-4">
                {{ title }}
            </div>
            <div class="subtitle is-6">
                {{ subtitle }}
            </div>
        </div>
    </div>
{% endmacro %}


{% macro user_single(user, show_user=true, is_self=false) %}
    {% macro _footer() %}
        <div class="card-footer-item">
            Registered:&ensp;
            {{ user.created|moment }}
        </div>
        {% if is_self %}
        <div class="card-footer-item">
            <a href="{{ url_for('user.change') }}">
                Change Data
            </a>
        </div>
        {% endif %}
        <div class="card-footer-item">
            Last Login:&ensp;
            {{ user.last_login|moment }}
        </div>
    {% endmacro %}

    {% call() _card(footer=_footer()) %}
        {% with len = user.crawls|length %}
        {{ _media(
            user.icon, user.username,
            len ~ ' ' ~ ('Crawls' if len != 1 else 'Crawl')
        ) }}
        {% endwith %}
        {% if user.crawls %}
            <div class="content">
                {{ crawls_list(user.crawls, show_user=show_user) }}
            </div>
        {% elif is_self %}
            <div class="content">
                <div class="field is-grouped is-grouped-centered">
                    <div class="control">
                        <a
                           class="button is-medium"
                           href="{{ url_for('crawl.index') }}"
                        >
                            <span class="icon">
                                <i class="fas fa-paint-brush"></i>
                            </span>
                            <span>Crawl</span>
                        </a>
                    </div>
                </div>
            </div>
        {% endif %}
    {% endcall %}
{% endmacro %}

{% macro crawl_single(crawl) %}
    {% macro _footer() %}
        <div class="card-footer-item">
            Created:&ensp;
            {{ crawl.created|moment }}
        </div>
        <div class="card-footer-item">
            TTL:&ensp;
            {{ crawl.ttl }}
        </div>
        <div class="card-footer-item">
            User:&ensp;
            <a href="{{ url_for('main.user_single', prime=crawl.user.prime) }}">
                {{ crawl.user.username }}
            </a>
        </div>
    {% endmacro %}

    {% call() _card(footer=_footer()) %}
        {% with len = crawl.urls|length %}
        {{ _media(
            'fa-flask', 'Crawl',
            len ~ ' ' ~ ('URLs' if len != 1 else 'URL')
        ) }}
        {% endwith %}
        {% if crawl.urls %}
            <div class="content">
                {{ urls_list(crawl.urls, show_crawls=false) }}
            </div>
        {% endif %}
    {% endcall %}
{% endmacro %}

{% macro url_single(url) %}
    {% macro _footer() %}
        <div class="card-footer-item">
            Created:&ensp;
            {{ url.created|moment }}
        </div>
        <div class="card-footer-item">
            Hop:&ensp;
            {{ url.hop }}
        </div>
        <div class="card-footer-item">
            Crawl:&ensp;
            <a href="{{ url_for('main.crawl_single', prime=url.crawl.prime) }}">
                {{ url.crawl.created|moment }}
            </a>
        </div>
    {% endmacro %}
    {% macro _link() %}
        <a href="{{ url.address }}">
            {{ url.address|truncate(config.TRUNCATE, end='...') }}
        </a>
    {% endmacro %}
    {% macro _state() %}
        {% with (icls, icon) = (
            'has-text-success', 'fa-award'
        ) if url.status.good else (
            'has-text-danger', 'fa-fire-alt'
        ) %}
            <span class="icon {{ icls }}" style="display: inline-table;">
                <i class="fas {{ icon }}"></i>
            </span>
        {% endwith %}
        <strong>{{ url.status.value }}</strong>
    {% endmacro %}
    {% macro _line(title, value) %}
        {% if value %}
            <div class="level">
                <div class="level-left">
                    <div class="level-item">
                        <div class="title is-4">
                            {{ title }}
                        </div>
                    </div>
                </div>
                <div class="level-right">
                    <div class="level-item">
                        {{ value }}
                    </div>
                </div>
            </div>
        {% endif %}
    {% endmacro %}

    {% call() _card(footer=_footer()) %}
        {{ _media(
            'fa-vial', _link(),
            _state()
        ) }}
        {% if url.error.value %}
        <div class="card-content has-text-centered">
            <code>{{ url.error.value }}</code>
        </div>
        {% endif %}
        <div class="card-content">
            {{ _line('Scheme', url.scheme.value) }}
            {{ _line('Username', url.username.value) }}
            {{ _line('Password', url.password.value) }}
            {{ _line('Thirdlevel', url.thirdlevel.value) }}
            {{ _line('Secondlevel', url.secondlevel.value) }}
            {{ _line('Toplevel', url.toplevel.value) }}
            {{ _line('Port', url.port.value) }}
            {{ _line('Path', url.path.value) }}
            {{ _line('Argument', url.argument.value) }}
            {{ _line('Fragment', url.fragment.value) }}
        </div>
        {% if url.parent %}
        <div class="title is-4 has-text-centered">
            Parent
        </div>
        {{ urls_list([url.parent], show_crawls=false) }}
        {% endif %}
        {% if url.children %}
        <div class="title is-4 has-text-centered">
            Children
        </div>
        {{ urls_list(url.children, show_crawls=false) }}
        {% endif %}
    {% endcall %}
{% endmacro %}