spiderpig/spiderpig/models/crawl.py
from spiderpig.base import DB
from spiderpig.models.base import Model, db_pri_col, db_ref_rel


class Crawl(Model):
    __tablename__ = 'crawl'

    ttl = DB.Column(DB.Integer(), nullable=False, default=0)
    user_prime = db_pri_col('user', False)
    urls = db_ref_rel('Url', 'crawl')

spiderpig/spiderpig/forms/crawl.py
from wtforms import IntegerField, StringField, SubmitField
from wtforms.validators import URL, InputRequired, NumberRange

from flask_wtf import FlaskForm
from spiderpig.fixed import FORM_CRAWL_TTL_MAX, FORM_CRAWL_TTL_MIN


class SnapForm(FlaskForm):
    address = StringField('Address', validators=[
        InputRequired(),
        URL(message='This does not look like an URL')
    ], description='Where should I start?')
    ttl = IntegerField('Time to live', validators=[
        InputRequired(),
        NumberRange(
            min=FORM_CRAWL_TTL_MIN, max=FORM_CRAWL_TTL_MAX,
            message='Should be between %(min)s and %(max)s',
        )
    ], description='How far should I go?')

    submit = SubmitField('Submit')

spiderpig/spiderpig/views/crawl.py
from flask import (
    Blueprint, Response, abort, render_template, request, stream_with_context,
)
from flask.json import dumps

from flask_login import current_user, login_required
from spiderpig.crawl.spider import Spider
from spiderpig.fixed import FORM_CRAWL_TTL_DEFAULT
from spiderpig.forms.crawl import SnapForm

BLUEPRINT_CRAWL = Blueprint('crawl', __name__, url_prefix='/crawl')


@BLUEPRINT_CRAWL.route('/', methods=['GET', 'POST'])
@login_required
def index():
    form = SnapForm(
        address=request.args.get('address'),
        ttl=request.args.get('ttl', FORM_CRAWL_TTL_DEFAULT),
    )
    submitted = form.validate_on_submit()

    return render_template(
        'crawl/index.html',
        title='Crawl',
        form=form,
        submitted=submitted,
    )


@BLUEPRINT_CRAWL.route('/snap', methods=['POST'])
@login_required
def snap():
    address = request.values.get('address', None)
    ttl = request.values.get('ttl', None)
    if not address or not ttl:
        abort(400)
    try:
        ttl = int(ttl)
    except ValueError:
        abort(400)

    spider = Spider()
    def collect():
        for elem in spider(address=address, ttl=ttl, user=current_user):
            yield '{}\n\t\t\n'.format(dumps(elem.view()))

    return Response(
        stream_with_context(collect()),
        status=200,
        mimetype='text/plain'
    )

spiderpig/spiderpig/templates/crawl/index.html
{% extends 'page.html' %}
{% from 'macros/form.html' import render_form %}

{% block main_head %}
    <script src="{{ url_for('static', filename='crawl.js') }}" type="text/javascript"></script>
{% endblock %}

{% block content %}
    {% if not submitted %}
        {{ render_form(form) }}
    {% else %}
    <div class="content">
        <progress id="snapbar" class="progress is-link" value="0" max="1"></progress>
    </div>
    <div id="snapcontent" class="content"></div>
    <script type="text/javascript">
        ; +(function () {
            'use strict';
            document.addEventListener("DOMContentLoaded", function () {
                ctrl(
                    "{{ url_for('crawl.snap') }}",
                    '{{ form.address.data|urlencode }}',
                    '{{ form.ttl.data|urlencode }}',
                    '{{ form.csrf_token.data|urlencode }}',
                    'snapcontent', 'snapbar'
                );
            });
        })();
    </script>
    {% endif %}
{% endblock %}