spiderpig/spiderpig/models/base.py
from spiderpig.base import DB
from spiderpig.models.mixin_base import CreatedMixin, CRUDMixin, PrimaryMixin
from spiderpig.models.mixin_urls import ValueIntMixin, ValueStrMixin


class Model(CreatedMixin, PrimaryMixin, CRUDMixin, DB.Model):
    __table_args__ = {'extend_existing': True}
    __abstract__ = True


class UrlIntModel(ValueIntMixin, Model):
    __abstract__ = True


class UrlStrModel(ValueStrMixin, Model):
    __abstract__ = True


def db_pri_col(name: str, nullable: bool = True):
    name = '{}.prime'.format(name)
    return DB.Column(DB.Integer(), DB.ForeignKey(name), nullable=nullable)


def db_ref_rel(tbl: str, bref: str, *, self_rel: bool = False):
    return DB.relationship(
        tbl, backref=bref, lazy='joined',
        remote_side='{}.prime'.format(tbl) if self_rel else None,
        order_by='{}.created.desc()'.format(tbl),
    )

spiderpig/spiderpig/views/crawl.py
from flask import (
    Blueprint, Response, abort, render_template, request, stream_with_context,
)
from flask.json import dumps

from flask_login import current_user, login_required
from spiderpig.crawl.spider import Spider
from spiderpig.fixed import FORM_CRAWL_TTL_DEFAULT
from spiderpig.forms.crawl import SnapForm

BLUEPRINT_CRAWL = Blueprint('crawl', __name__, url_prefix='/crawl')


@BLUEPRINT_CRAWL.route('/', methods=['GET', 'POST'])
@login_required
def index():
    form = SnapForm(
        address=request.args.get('address'),
        ttl=request.args.get('ttl', FORM_CRAWL_TTL_DEFAULT),
    )
    submitted = form.validate_on_submit()

    return render_template(
        'crawl/index.html',
        title='Crawl',
        form=form,
        submitted=submitted,
    )


@BLUEPRINT_CRAWL.route('/snap', methods=['POST'])
@login_required
def snap():
    address = request.values.get('address', None)
    ttl = request.values.get('ttl', None)
    if not address or not ttl:
        abort(400)
    try:
        ttl = int(ttl)
    except ValueError:
        abort(400)

    spider = Spider()
    def collect():
        for elem in spider(address=address, ttl=ttl, user=current_user):
            yield '{}\n\t\t\n'.format(dumps(elem.view()))

    return Response(
        stream_with_context(collect()),
        status=200,
        mimetype='text/plain'
    )

spiderpig/spiderpig/views/main.py
from flask import Blueprint, render_template

from spiderpig.fixed import (
    LATEST_CRAWL_NUM, LATEST_URL_NUM, LATEST_USER_NUM, PAGE_CRAWL_NUM,
    PAGE_URL_NUM, PAGE_USER_NUM,
)
from spiderpig.models.crawl import Crawl
from spiderpig.models.url import Url
from spiderpig.models.user import User

BLUEPRINT_MAIN = Blueprint('main', __name__)


@BLUEPRINT_MAIN.route('/')
def index():

    num_url = Url.query.count()
    num_url_fail = Url.query_filter_fail().count()
    num_url_good = (num_url - num_url_fail)

    return render_template(
        'main/index.html',
        num_user=User.query.count(),
        num_crawl=Crawl.query.count(),
        num_url=num_url,
        num_url_fail=num_url_fail,
        num_url_good=num_url_good,
        lat_user=User.query_order_created().limit(LATEST_USER_NUM).all(),
        lat_crawl=Crawl.query_order_created().limit(LATEST_CRAWL_NUM).all(),
        lat_url=Url.query_order_created().limit(LATEST_URL_NUM).all(),
    )


@BLUEPRINT_MAIN.route('/users/<int:page>')
@BLUEPRINT_MAIN.route('/users/')
@BLUEPRINT_MAIN.route('/users')
def users(page=None):

    return render_template(
        'main/user.html',
        title='Users',
        users=User.query_order_created().paginate(
            page, per_page=PAGE_USER_NUM
        ),
    )


@BLUEPRINT_MAIN.route('/user/<int:prime>')
def user_single(prime):
    user = User.query.get_or_404(prime)

    return render_template(
        'main/user.html',
        title='{} User'.format(user.username),
        user=user,
    )


@BLUEPRINT_MAIN.route('/crawls/<int:page>')
@BLUEPRINT_MAIN.route('/crawls/')
@BLUEPRINT_MAIN.route('/crawls')
def crawls(page=None):

    return render_template(
        'main/crawl.html',
        title='Crawls',
        crawls=Crawl.query_order_created().paginate(
            page, per_page=PAGE_CRAWL_NUM
        ),
    )


@BLUEPRINT_MAIN.route('/crawl/<int:prime>')
def crawl_single(prime):
    crawl = Crawl.query.get_or_404(prime)

    return render_template(
        'main/crawl.html',
        title='Crawl details',
        crawl=crawl,
    )


@BLUEPRINT_MAIN.route('/urls/<int:page>')
@BLUEPRINT_MAIN.route('/urls/')
@BLUEPRINT_MAIN.route('/urls')
def urls(page=None):

    return render_template(
        'main/url.html',
        title='URLs',
        urls=Url.query_order_created().paginate(
            page, per_page=PAGE_URL_NUM
        ),
    )


@BLUEPRINT_MAIN.route('/url/<int:prime>')
def url_single(prime):
    url = Url.query.get_or_404(prime)

    return render_template(
        'main/url.html',
        title='URL details',
        url=url,
    )


@BLUEPRINT_MAIN.route('/urls/good/<int:page>')
@BLUEPRINT_MAIN.route('/urls/good/')
@BLUEPRINT_MAIN.route('/urls/good')
def urls_good(page=None):

    return render_template(
        'main/url.html',
        title='Good URLs',
        urls=Url.query_filter_good(
            query=Url.query_order_created()
        ).paginate(
            page, per_page=PAGE_URL_NUM
        )
    )


@BLUEPRINT_MAIN.route('/urls/fail/<int:page>')
@BLUEPRINT_MAIN.route('/urls/fail/')
@BLUEPRINT_MAIN.route('/urls/fail')
def urls_fail(page=None):

    return render_template(
        'main/url.html',
        title='Failed URLs',
        urls=Url.query_filter_fail(
            query=Url.query_order_created()
        ).paginate(
            page, per_page=PAGE_URL_NUM
        )
    )

spiderpig/spiderpig/views/side.py
from flask import Blueprint, current_app, render_template, request, url_for
from werkzeug.contrib.atom import AtomFeed, FeedEntry

from spiderpig.fixed import FEED_CRAWL_NUM, FEED_URL_NUM, FEED_USER_NUM
from spiderpig.forms.find import FindForm
from spiderpig.models.crawl import Crawl
from spiderpig.models.url import Url
from spiderpig.models.user import User

BLUEPRINT_SIDE = Blueprint('side', __name__)


@BLUEPRINT_SIDE.route('/about')
def about():

    return render_template(
        'side/about.html',
        title='About',
    )


@BLUEPRINT_SIDE.route('/find', methods=['GET', 'POST'])
def find():
    def _search(query):
        for url in Url.query_order_created().all():
            if any((
                    query in str(url.status.value),
                    url.error and query in url.error.value,
                    query in url.address
            )):
                yield url

    query = request.args.get('q') or request.form.get('query')
    if query:
        query = query.strip()
    results = None
    form = FindForm(query=query)

    if query:
        results = list(_search(query))

    return render_template(
        'side/find.html',
        title='Search',
        form=form,
        query=query,
        results=results,
    )


@BLUEPRINT_SIDE.route('/feed.xml')
def feed():
    def _entries():
        def _entry(*, title, content, endpoint, obj, user: User):
            return FeedEntry(
                title=title, title_type='text',
                content=content, content_type='html',
                url=url_for(endpoint, prime=obj.prime, _external=True),
                author={
                    'name': user.username,
                    'uri': url_for(
                        'main.user_single', prime=user.prime, _external=True
                    ),
                },
                published=obj.created,
                updated=obj.created,
            )

        return (fl for at in (

            (_entry(
                title='User #{} ({})'.format(user.prime, user.username),
                content='''
<dl>
    <dt>User</dt>
    <dd>#{prime} ({username})</dd>
    <dt>Crawls</dt>
    <dd>{crawls}</dd>
</dl>
                '''.strip().format(
                    prime=user.prime,
                    username=user.username,
                    crawls=len(user.crawls),
                ),
                endpoint='main.user_single',
                obj=user, user=user,
            ) for user in User.query_order_created().limit(
                FEED_USER_NUM
            ).all()),

            (_entry(
                title='Crawl #{}'.format(crawl.prime),
                content='''
<dl>
    <dt>Crawl</dt>
    <dd>#{prime}</dd>
    <dt>Urls</dt>
    <dd>{urls}</dd>
    <dt>User</dt>
    <dd>#{user_prime} ({username})</dd>
</dl>
                '''.strip().format(
                    prime=crawl.prime,
                    urls=len(crawl.urls),
                    user_prime=crawl.user.prime,
                    username=crawl.user.username,
                ),
                endpoint='main.crawl_single',
                obj=crawl, user=crawl.user,
            ) for crawl in Crawl.query_order_created().limit(
                FEED_CRAWL_NUM
            ).all()),

            (_entry(
                title='URL #{}'.format(url.prime),
                content='''
<dl>
    <dt>URL</dt>
    <dd>#{prime}</dd>
    <dt>Address</dt>
    <dd><a href="{address}">{address}</a><dd>
    <dt>Status</dt>
    <dd>{status}</dd>
    <dt>Error</dt>
    <dd><code>{error}</code></dd>
    <dt>Crawl</dt>
    <dd>#{crawl_prime}</dd>
    <dt>User</dt>
    <dd>#{user_prime} ({username})</dd>
</dl>
                '''.strip().format(
                    prime=url.prime,
                    address=url.address,
                    status=url.status.value,
                    error=url.error.value if url.error else '-',
                    crawl_prime=url.crawl.prime,
                    user_prime=url.crawl.user.prime,
                    username=url.crawl.user.username,
                ),
                endpoint='main.url_single',
                obj=url, user=url.crawl.user,
            ) for url in Url.query_order_created().limit(
                FEED_URL_NUM
            ).all()),

        ) for fl in at)

    app_name = current_app.config['APP_NAME']
    app_subtitle = current_app.config['APP_SUBTITLE']
    url = url_for('main.index', _external=True)

    return AtomFeed(
        title='{} News Feed'.format(app_name), title_type='text',
        subtitle=app_subtitle, subtitle_type='text',
        url=url, feed_url=url_for('side.feed', _external=True),
        generator=(app_name, url, 'NaN'),
        entries=sorted(
            _entries(), reverse=True,
            key=lambda entry: entry.updated,
        ),
    ).get_response()

spiderpig/spiderpig/views/user.py
from flask import (
    Blueprint, abort, current_app, flash, redirect, render_template, request,
    url_for,
)

from flask_login import current_user, login_required, login_user, logout_user
from spiderpig.base import LMAN
from spiderpig.forms.user import ChangeForm, LoginForm, RegisterForm
from spiderpig.models.user import User

BLUEPRINT_USER = Blueprint('user', __name__, url_prefix='/user')


@LMAN.user_loader
def load_user(user_prime):
    return User.by_prime(user_prime)


def redirect_user_next():
    if not current_user.is_authenticated:
        return None
    redir = request.args.get('next')
    return redirect(redir if redir else url_for('user.home'))


@BLUEPRINT_USER.route('/logout')
@login_required
def logout():
    logout_user()
    flash('See you soon!', 'is-success')
    return redirect(url_for('main.index'))


@BLUEPRINT_USER.route('/login', methods=['GET', 'POST'])
def login():
    redir = redirect_user_next()
    if redir:
        return redir

    form = LoginForm()

    if form.validate_on_submit():
        user = form.retrieve()
        if user:
            flash('Welcome {}!'.format(user.username), 'is-success')
            login_user(user, remember=form.remember.data)
            redir = redirect_user_next()
            if redir:
                return redir

    return render_template(
        'user/handle.html',
        title='Login',
        form=form,
    )


@BLUEPRINT_USER.route('/register', methods=['GET', 'POST'])
def register():
    redir = redirect_user_next()
    if redir:
        return redir

    if not current_app.config['OPEN_REGISTRATION']:
        abort(404)

    form = RegisterForm()

    if form.validate_on_submit():
        user = form.retrieve()
        if user:
            flash('Hello {}! You are new here!'.format(user.username))
            login_user(user, remember=False)
            redir = redirect_user_next()
            if redir:
                return redir

    return render_template(
        'user/handle.html',
        title='Register',
        form=form,
    )


@BLUEPRINT_USER.route('/change', methods=['GET', 'POST'])
@login_required
def change():
    user = User.by_prime(current_user.prime)

    form = ChangeForm(icon=user.icon)

    if form.validate_on_submit():
        if form.retrieve(user):
            flash('Changed!')
            redir = redirect_user_next()
            if redir:
                return redir

    return render_template(
        'user/change.html',
        title='Change',
        form=form,
    )

@BLUEPRINT_USER.route('/home')
@login_required
def home():
    user = User.by_prime(current_user.prime)

    return render_template(
        'user/home.html',
        title='{} Home'.format(user.username),
        user=user,
    )

spiderpig/spiderpig/templates/_ico.html
<link rel="apple-touch-icon" sizes="60x60" href="{{ url_for('static', filename='ico/apple-touch-icon-60x60.png') }}">
<link rel="apple-touch-icon" sizes="76x76" href="{{ url_for('static', filename='ico/apple-touch-icon-76x76.png') }}">
<link rel="apple-touch-icon" sizes="120x120" href="{{ url_for('static', filename='ico/apple-touch-icon-120x120.png') }}">
<link rel="apple-touch-icon" sizes="152x152" href="{{ url_for('static', filename='ico/apple-touch-icon-152x152.png') }}">
<link rel="apple-touch-icon" sizes="180x180" href="{{ url_for('static', filename='ico/apple-touch-icon-180x180.png') }}">
<link rel="icon" type="image/png" sizes="32x32" href="{{ url_for('static', filename='ico/favicon-32x32.png') }}">
<link rel="icon" type="image/png" sizes="194x194" href="{{ url_for('static', filename='ico/favicon-194x194.png') }}">
<link rel="icon" type="image/png" sizes="192x192" href="{{ url_for('static', filename='ico/android-chrome-192x192.png') }}">
<link rel="icon" type="image/png" sizes="16x16" href="{{ url_for('static', filename='ico/favicon-16x16.png') }}">
<link rel="manifest" href="{{ url_for('static', filename='ico/site.webmanifest') }}">
<link rel="mask-icon" href="{{ url_for('static', filename='ico/safari-pinned-tab.svg') }}" color="#5bbad5">
<link rel="shortcut icon" href="{{ url_for('static', filename='ico/favicon.ico') }}">
<meta name="msapplication-TileColor" content="#ffc40d">
<meta name="msapplication-config" content="{{ url_for('static', filename='ico/browserconfig.xml') }}">
<meta name="theme-color" content="#ffffff">

spiderpig/spiderpig/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% if title is defined %}{{ title }} | {% endif %}{{ config.APP_NAME }}</title>
    {% include '_ico.html' %}
    <link rel="stylesheet" href="{{ url_for('static', filename='lib/bulma.min.css') }}" type="text/css">
    <script defer src="{{ url_for('static', filename='lib/fontawesome.min.js') }}" type="text/javascript"></script>
    <script defer src="{{ url_for('static', filename='lib/moment.min.js') }}" type="text/javascript"></script>
    {% block main_head %}{% endblock %}
</head>
<body>
    {% include 'navigation.html' %}
    {% block main_content %}{% endblock %}
    {% include 'footer.html' %}
    <script defer src="{{ url_for('static', filename='site.js') }}" type="text/javascript"></script>
</body>
</html>

spiderpig/spiderpig/templates/footer.html
<footer class="footer">
    <div class="container">
        <nav class="navbar">
            <div class="navbar-brand">
                <a class="navbar-item" href="{{ url_for('side.about') }}">
                    <span class="icon">
                        <i class="fas fa-tint"></i>
                    </span>
                    <span>{{ config.APP_NAME }}</span>
                </a>
                <a
                   class="navbar-item is-hidden-desktop"
                   href="{{ url_for('side.find') }}"
                >
                    <span class="icon">
                        <i class="fas fa-search"></i>
                    </span>
                </a>
                <a
                   class="navbar-item is-hidden-desktop"
                   href="{{ url_for('side.feed') }}"
                   target="_blank"
                >
                    <span class="icon">
                        <i class="fas fa-rss"></i>
                    </span>
                </a>
            </div>
            <div class="navbar-menu">
                <div class="navbar-start">
                    <div class="navbar-item">
                        {{ config.APP_SUBTITLE }}
                    </div>
                </div>
                <div class="navbar-end">
                    <a
                       class="navbar-item is-hidden-touch"
                       href="{{ url_for('side.find') }}"
                    />
                        <span class="icon">
                            <i class="fas fa-search"></i>
                        </span>
                        <span>Search</span>
                    </a>
                    <a
                       class="navbar-item is-hidden-touch"
                       href="{{ url_for('side.feed') }}"
                       target="_blank"
                    >
                        <span class="icon">
                            <i class="fas fa-rss"></i>
                        </span>
                        <span>Feed</span>
                    </a>
                </div>
            </div>
        </nav>
        <nav class="navbar is-size-7">
            <div class="navbar-menu">
                <div class="navbar-start">
                    <div class="navbar-item">
                        <span class="icon">
                            <i class="fas fa-code"></i>
                        </span>
                        written with
                        <span class="icon">
                            <i class="fas fa-heart"></i>
                        </span>
                        by my
                        <span class="icon">
                            <i class="fas fa-cat"></i>
                        </span>
                    </div>
                </div>
                <div class="navbar-end">
                    <div class="navbar-item">
                        <span>
                            Source code licensed
                            <a href="https://opensource.org/licenses/MIT">
                                MIT
                            </a>
                        </span>
                    </div>
                </div>
            </div>
        </nav>
    </div>
</footer>

spiderpig/spiderpig/templates/message.html
{% with flashed = get_flashed_messages(with_categories=true) %}
{% if flashed %}
<section class="section">
    <div class="container">
        <div class="columns">
            <div class="column is-10-desktop is-offset-1-desktop">
                {% for category, message in flashed %}
                <article class="message {{ category if category else 'is-dark' }}">
                    <div class="message-body">
                        {{ message }}
                    </div>
                </article>
                {% endfor %}
            </div>
        </div>
    </div>
</section>
{% endif %}
{% endwith %}

spiderpig/spiderpig/templates/navigation.html
<nav class="navbar has-shadow is-spaced">
    <div class="container">
        <div class="navbar-brand">
            <a class="navbar-item" href="{{ url_for('main.index') }}">
                <span class="icon">
                    <i class="fas fa-tint"></i>
                </span>
                <span>{{ config.APP_NAME }}</span>
            </a>

            <div class="navbar-burger" id="navBurger">
                <span></span>
                <span></span>
                <span></span>
            </div>
        </div>

        <div class="navbar-menu" id="navToggle">
            <div class="navbar-start">

                <a class="navbar-item" href="{{ url_for('main.users') }}">
                    <span class="icon">
                        <i class="fas fa-users"></i>
                    </span>
                    <span>Users</span>
                </a>

                <a class="navbar-item" href="{{ url_for('main.crawls') }}">
                   <span class="icon">
                       <i class="fas fa-flask"></i>
                   </span>
                   <span>Crawls</span>
                </a>

                <a class="navbar-item" href="{{ url_for('main.urls') }}">
                    <span class="icon">
                        <i class="fas fa-vial"></i>
                    </span>
                    <span>URLs</span>
                </a>

                {% if current_user.is_authenticated %}
                <a class="navbar-item" href="{{ url_for('user.home') }}">
                    <span class="icon">
                        <i class="fas {{ current_user.icon }}"></i>
                    </span>
                    <span>{{ current_user.username }}</span>
                </a>
                {% endif %}
            </div>

            <div class="navbar-end">

                <div class="navbar-item">
                    <div class="field is-grouped is-grouped-multiline">
                        <p class="control">
                            {% if current_user.is_authenticated %}
                            <a class="button" href="{{ url_for('user.logout') }}">
                                <span class="icon">
                                    <i class="fas fa-user-minus"></i>
                                </span>
                                <span>Logout</span>
                            </a>
                            {% else %}
                            <a class="button" href="{{ url_for('user.login') }}">
                                <span class="icon">
                                    <i class="fas fa-user-check"></i>
                                </span>
                                <span>Login</span>
                            </a>
                            {% endif %}
                        </p>
                    </div>
                </div>

                {% if current_user.is_authenticated %}
                <div class="navbar-item">
                    <div class="field is-grouped is-grouped-multiline">
                        <p class="control">
                            <a class="button" href="{{ url_for('crawl.index') }}">
                                <span class="icon">
                                    <i class="fas fa-paint-brush"></i>
                                </span>
                                <span>Crawl</span>
                            </a>
                        </p>
                    </div>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</nav>

spiderpig/spiderpig/templates/page.html
{% extends 'base.html' %}
{% from 'macros/base.html' import nothing_there %}

{% block main_content %}
    <section class="hero is-dark">
        <div class="hero-body">
            <div class="container">
                <div class="columns">
                    <div class="column is-10-desktop is-offset-1-desktop">
                        <h1 class="title is-2 is-spaced">
                            {{ title|d(config.APP_NAME) }}
                        </h1>
                    </div>
                </div>
            </div>
        </div>
    </section>
    {% include 'message.html' %}
    <section class="section">
        <div class="container">
            <div class="columns">
                <div class="column is-10-desktop is-offset-1-desktop">
                    {% block content %}{{ nothing_there() }}{% endblock %}
                </div>
            </div>
        </div>
    </section>
{% endblock %}